### ISSUE TITLE
Auhentication refresh token

### ISSUE THREAD

**Issue by NikoGrano** [GameTactic/Room#200]
In version `c6bd8c88daf0b70d901585e7236f03ea8118b5ab` of authentication microservice refreshing tokens being to be possible. You should now refresh your client token automatically if that is about to expire.

Endpoint is available via `GET` on `/refresh/{token}`.

**Comment by Ataww** [comment]
What is the expected expiration interval? Is it provider specific?

**Comment by NikoGrano** [comment]
Expiration is currently 1 day or with Readme enabled 1 month. These values can change without warning. Therefore you should check token expiration and based on that decide when to renew token. 

I would myself renew the token only if it's expiring within next 5 minutes.

**Comment by NikoGrano** [comment]
@Ataww Please update

**Comment by bryansamuel1** [comment]
I have added refresh in the latest PR @NikoGrano we can close this then?

**Comment by NikoGrano** [comment]
Closed as of #187
