### ISSUE TITLE
Translations are locked to specific commit instead of using latest

### ISSUE THREAD

**Issue by NikoGrano** [GameTactic/Room#202]
Fixing bug introduced by @bryansamuel1 

You should lock sub module always to branch, not commit like I said... 
https://git-scm.com/docs/git-submodule

**Comment by bryansamuel1** [comment]
You don't need to tag the person who created the bug in these tickets @NikoGrano. FYI.

**Comment by NikoGrano** [comment]
Not blaming, only trying to show this, so you know next time.... Everyone needs to learn here.

**Comment by NikoGrano** [comment]
clsoed in #203
