### ISSUE TITLE
Set up a Vue application

### ISSUE THREAD

**Issue by bryansamuel1** [GameTactic/Room#5]
Create a Vue JS shell .

- Investigate the uses and choices for a CSS framework
- Investigate 3rd party canvas components that we could use
- Investigate UI UX designs for mobile first development

**Comment by Ataww** [comment]
How far have you digged for the points above? 

You already have vuetify set for the first point, would that be enough or do you think of another tool to complement it?

Second point I have no idea tbh

Third point we should probably do some mock screens to see how to arrange elements on mobile, however I believe with the right containers it shouldn't be too hard to make a decently responsive application. Making it a pleasant experience on mobile is gonna be very tricky for tactic edition

**Comment by bryansamuel1** [comment]
Vuetify has everything covered so far so I see no need to use any other framework. We have scss set up too along with global variables so we can change the colour  theme of the whole app easily.

I am trying out Vue konva this week. So far it is very promising and has alot of power behind it. If you find alternatives let me know. 

We were thinking of just having the canvas and navbar only on mobile. More of a view only at there are too many editing options to fit on the screen. Then with a tablet up to a desktop we will include all options to the user. Thoughts? 

We will go through the whole app on Sunday as I have lots of bits I want to discuss about the functionality and design

**Comment by NikoGrano** [comment]
Closed as stale
