### ISSUE TITLE
MVP1 - Authorisation

### ISSUE THREAD

**Issue by bryansamuel1** [GameTactic/Room#51]
Need to set up the room to work with authorisation. This ticket will focus on the storing of user permissions in the microservice.

There will be 1 permission in the app for now. **Admin**.

**Comment by bryansamuel1** [comment]
@NikoGrano I have created this ticket for the permissions in the room component, but for the back end microservice work., Can you update and move this ticket to the appropriate place?

**Comment by NikoGrano** [comment]
@bryansamuel1 I do not know what is even this ticket. If there is no need for this ticket, please close.
