### ISSUE TITLE
MVP1 - Set up Layout

### ISSUE THREAD

**Issue by bryansamuel1** [GameTactic/Room#59]
This issue will cover the structure of the GameTactic.
Components within each section should be placeholders for now.
Should be responsive

All except Mobile resolutions
- [x] Top Left Logo Bar
- [x] Top Right Settings Bar
- [x] Left Map Tools Bar
- [x] Right Entity Bar
- [x] Central Canvas

Mobile
- [x] Top Left Logo Bar
- [x ] Central Canvas

**Comment by bryansamuel1** [comment]
@Ataww are you still ok to carry on with this issue? Once my code is in dev you should have enough of the basis to finish off the remaining 2 items.

I am going to get hold of the Konva developer (Anton) to discuss responsive canvas, as the documentation is very light on the subject and what I have seen and tried is insufficient. With help from Anton it should allow the central Canvas to respond perfectly as a user flicks between resolutions, which is also necessary if they rotate their phones from landscape to portrait or vice versa.

**Comment by Ataww** [comment]
I'm closing this issue. Main elements have been placed and we can refined the design later
