### ISSUE TITLE
Set up docker / debian / echo server locally and set up websockets to recieve and transmit ping data packet

### ISSUE THREAD

**Issue by bryansamuel1** [GameTactic/Room#62]

**Comment by Niko9911** [comment]
Not possible on Windows without Windows Pro to run docker containers. It is possible to build the binary from the sources for the Windows, however there is no guide how to do it and I do not know how.

This can be achived only by running full VM instance or compiling sources in subsystem and running the binary manually.

Full documentation to use this https://github.com/GameTactic/CPP-Echo

Closing as non-related.
